### ISSUE TITLE
Transaction error

### ISSUE THREAD

**Issue by omdv** [ethers-io/ethers.io#10]
I am trying to transfer ETH to other wallet and it keeps saying "There was an error with your transaction". I tried to reduce the amount to allow a larger fee, but it keeps giving error regardless.

**Comment by ricmoo** [comment]
How much room are you leaving for the fee? Ethers is currently set up to allow contracts to execute, which means it leaves a larger buffer (gas limit) when sending transactions. We are adding a feature to make selecting a gas limit easier (as well as automatically select a better estimate based on target address and data).

The actual fee won't be any larger, but it needs more "room" for the fee.

If you need to clear out the account entirely, you can use MyEtherWallet to import your JSON file, since it may take us a while to get these changes in place.

If you have any further issues, please contact us at support@ethers.io.

Thanks, and sorry for the inconvenience.

**Comment by omdv** [comment]
Thank you for the reply. I actually figured out experimentally that the room is quite big. Thanks.
